/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CaAgendamentoEntrada extends javax.swing.JDialog {

    /**
     * Creates new form FoAdicionarAlunos
     */
    
    private Conexao c;
    private Integer Consulta;
    private Integer SelectCodConsulta = Consulta;
    
    public CaAgendamentoEntrada(Integer Consulta) {
        initComponents();
        this.setModal(true);
        this.c = new Conexao();
        this.Consulta = Consulta;
        
        
    //Carregar combobox
        this.c.setComboBoxPaciente(CBPaciente, "pacientes");
    
    
    //Edição
        if (Consulta!=-1) {
            this.setTitle("Editar");
            btnCadastrar.setText("Editar");
            
            //Carregar os campos
            try {
                String SQL = " SELECT C.idconsultas,C.dataconsulta,P.nomepaciente FROM consultas as C INNER JOIN pacientes as P ON C.idpaciente = P.idpaciente WHERE C.idconsultas = "+Consulta;
                this.c.setResultSet(SQL);
                this.c.getResultSet().first();
                txtDataConsulta.setText(this.c.getResultSet().getString("C.dataconsulta"));  
                CBPaciente.setSelectedItem(this.c.getResultSet().getString("P.nomepaciente"));
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDataConsulta = new javax.swing.JFormattedTextField();
        btnNovoPaciente = new javax.swing.JButton();
        CBPaciente = new javax.swing.JComboBox<>();
        lblData = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");

        try {
            txtDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataConsultaActionPerformed(evt);
            }
        });

        btnNovoPaciente.setText("Novo");
        btnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPacienteActionPerformed(evt);
            }
        });

        CBPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPacienteActionPerformed(evt);
            }
        });

        lblData.setText("Data Consulta");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblPaciente.setText("Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataConsulta)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CBPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPaciente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnNovoPaciente)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnNovoPaciente)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPacienteActionPerformed
        // TODO add your handling code here:
        new CaPacientesEntrada(-1).setVisible(true);
        //Carregar combobox
        this.c.setComboBoxPaciente(CBPaciente, "pacientes");
    }//GEN-LAST:event_btnNovoPacienteActionPerformed

    private void CBPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPacienteActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtDataConsulta.getText().equals("    -  -  ")) {
            JOptionPane.showMessageDialog(this, "Informar a Data da Consulta");
            txtDataConsulta.requestFocus();
        }
        else if (CBPaciente.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(this, "Selecione o Paciente");
            CBPaciente.requestFocus();
        }
        else {       
            String SQL;
            String Msg;
            
            //Cadastrar
            if (this.Consulta == -1) {
                Msg = "Registro adicionado com sucesso";
                SQL = "INSERT INTO consultas (dataconsulta,idpaciente) VALUES ('"+ txtDataConsulta.getText() +"','"+this.c.getCodigoComboBoxPacientes(CBPaciente,"Paciente")+"')";
            }                                                                                                                       
            //Editar
            else {
                Msg = "Registro editado com sucesso";
                SQL = "UPDATE consultas SET dataconsulta = '"+txtDataConsulta.getText()+"',idpaciente = '"+this.c.getCodigoComboBoxPacientes(CBPaciente, "pacientes")+"' WHERE idconsultas = "+Consulta;                              
            }
            this.c.SQLExecute(SQL);
            JOptionPane.showMessageDialog(this, Msg);
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataConsultaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPaciente;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnNovoPaciente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JFormattedTextField txtDataConsulta;
    // End of variables declaration//GEN-END:variables
}
